version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: laravel.php-httpd.Dockerfile
    environment:
      - GITHUB_USER_NAME=${GITHUB_USER_NAME}
      - GITHUB_USER_EMAIL=${GITHUB_USER_EMAIL}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    image: jianzhong/php74_httpd_laravel
    container_name: web
    volumes:
      - ..:/var/www/app
    ports:
      - 80:80
    networks:
      - app_db_net

  db:
    image: mariadb
    container_name: db
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app_db_net

volumes:
  db_volume:

networks:
  app_db_net:
  