version: '3.7'
services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ..:/var/www/app
      - ./files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web_net
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: laravel.fpm.Dockerfile
    environment:
      - GITHUB_USER_NAME=${GITHUB_USER_NAME}
      - GITHUB_USER_EMAIL=${GITHUB_USER_EMAIL}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    image: jianzhong/php74_fpm_laravel
    container_name: php
    volumes:
      - ..:/var/www/app
    networks:
      - web_net
      - data_net

  db:
    image: mariadb
    container_name: db
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - data_net

volumes:
  db_volume:

networks:
  web_net:
  data_net:
  